pipeline v2

diff --git a/Jenkins_Pipeline b/Jenkins_Pipeline
--- a/Jenkins_Pipeline
+++ b/Jenkins_Pipeline
@@ -4,7 +4,7 @@ pipeline {
     imagename = "amuzhichenko/simple_web"
     registry = "registry.hub.docker.com"
     credential = 'dockerhub'
-    app_status = "sh  kubectl get pods --namespace=prod | grep my-app | awk '{print ${3}}'"
+    
 
   }
   
@@ -29,6 +29,17 @@ pipeline {
           sh "echo '$imagename:${env.BUILD_ID} was built!'"
           }
         }
+        
+        post {
+            success {
+                echo 'Compile Stage Successful . . .'
+            }
+            failure {
+                echo 'Compile stage failed'
+                error('Stopping early…')
+
+             }
+    }
     }
 
     
@@ -73,12 +84,37 @@ stage ("Deploy in pre-prod ns")  {
     sh "minikube start"    
     sh "minikube status"
     sh "kubectl run my-app --image=$imagename:${env.BUILD_ID} --namespace=pre-prod --port=8000"
+    sh "sleep 5"
 } 
     
   }
  
+ //stage ("Test deppoyment in pre-prod")  {
+     //steps {
+         
+
+        // sh """#!/bin/bash
+        
+        //app_status=`kubectl get pods --namespace=pre-prod | grep my-app | awk {\'print ${3}\'}'`
+       
+        
+        // if [ "$app_status" == "Running" ]
+        // then
+        // echo "Status deployment is $app_status"
+        // else
+        // echo "Deployment in pre-prod namespace was failed"
+        // exit 1
+        // fi
+    
+
+         
+   //  }
+     
+ //}
+ 
  
 stage("Manual approvment") {
+      //timeout(time: 5, unit: "MINUTES") {
             input {
                 message "Ready to deploy?"
                 ok "Yes"
@@ -87,12 +123,15 @@ stage("Manual approvment") {
                 echo "Deployment stage."
             }
         }
-  
-  
+
+
+
+
   stage ("Deploy in prod ns")  {
     steps {
     //sh "minikube start"    
     //sh "minikube status"
+    //sh "kubectl delete pod my-app --namespace=prod"
     sh "kubectl run my-app --image=$imagename:${env.BUILD_ID} --namespace=prod --port=8000"
 } 
     
@@ -106,6 +145,7 @@ stage("Manual approvment") {
   }
     }
        }
+  
   
   post ("Slack notification") {
             success {
